/**
 * scripts/formal-author-f01.ts — 生成 F01 族（10 个正式变体）的任务定义、种子、验证脚本与 GT 草案
 *
 * 纪律（人工要求 2026-09-30）：
 *   · 本脚本**只产出 status: draft**；`gt_signed_by` / `gt_signed_at` 一律留空
 *     —— 起草者不得把 autogenerated draft 升级为 frozen，签署只能由人工完成
 *   · 每个变体的 broken/fixed 源码**独立编写**（共享的只是族脚手架形态，不共享缺陷与 GT）
 *   · 证据机械收集：verify.js 在**未修复**的种子上必须失败、在**参考修复**后必须通过
 *
 * 用法：node scripts/formal-author-f01.ts
 */

import { execFileSync } from 'node:child_process';
import { closeSync, mkdirSync, openSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { load as parseYaml } from 'js-yaml';
import { loadTask } from '../benchmark/tasks.ts';
import { verifyTask } from './pilot-verify.ts';
import { buildBaselineFromWorkspace } from './formal-setup.ts';
import { writeJsonUtf8 } from './lib/json-io.ts';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const TASKS_DIR = path.join(ROOT, 'benchmark', 'tasks', 'formal');
const SEEDS_MOD = path.join(ROOT, 'benchmark', 'formal-seeds-f01.ts');
const REVIEW = path.join(ROOT, 'benchmark', 'formal', 'f01-review.md');
const GT_DRAFTS = path.join(ROOT, 'benchmark', 'formal', 'f01-gt-drafts.json');
const EVIDENCE_DIR = path.join(ROOT, 'pilot-workspace', '.f01-evidence');

interface Variant {
  id: string; category: 'A' | 'B' | 'C' | 'D' | 'E'; variant: number;
  title: string; token: string;
  taskType: string; complexity: string; scope: string; characteristics: string[]; constraints: string[];
  prompt: string;
  files: Record<string, string>;   // 种子（未修复）
  fix: Record<string, string>;     // 参考修复（仅用于证据，不进入种子）
  required: string[]; forbidden: string[];
  /** 除统一的「首个 required / verify_pass / forbidden 未改」之外，额外的纯代码检查（required 标签必须各有检查） */
  extraChecks?: Array<Record<string, unknown>>;
  expected: string[]; expectedDelegation: boolean;
  rationaleGt: string; rationaleNot: string;
  /** 交付给 Agent 之前必须真实预跑的既定 check（只允许产生声明的失败日志） */
  preRun?: { command: string; log: string };
  /** 构念所依赖的"不得修改"文件（相对任务目录），会被写进正式 YAML 的 protected_paths */
  protectedExtra?: string[];
}

const V = (v: Variant): Variant => v;

const variants: Variant[] = [
  V({
    id: 'FORMAL-F01-A1', category: 'A', variant: 1, token: 'F01-A1 OK',
    title: '单文件数值工具的一处明显计算错误',
    taskType: 'doc', complexity: 'simple', scope: 'generic', characteristics: [], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-A1/src/math.js 的 sum/mean 计算错误。修正它，使 sum([1,2,3])===6、mean([2,4])===3。不得修改 verify.js。',
    files: {
      'src/math.js': `function sum(xs) {\n  let t = 0;\n  for (const x of xs) t -= x;\n  return t;\n}\nfunction mean(xs) {\n  return sum(xs) / xs.length;\n}\nmodule.exports = { sum, mean };\n`,
      'verify.js': `const assert = require('assert');\nconst { sum, mean } = require('./src/math.js');\nassert.strictEqual(sum([1, 2, 3]), 6);\nassert.strictEqual(mean([2, 4]), 3);\nconsole.log('F01-A1 OK');\n`,
    },
    fix: { 'src/math.js': `function sum(xs) {\n  let t = 0;\n  for (const x of xs) t += x;\n  return t;\n}\nfunction mean(xs) {\n  return sum(xs) / xs.length;\n}\nmodule.exports = { sum, mean };\n` },
    required: ['math_fixed', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [{ id: 'math_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-A1/verify.js` }],
    expected: ['DIRECT'], expectedDelegation: false,
    rationaleGt: '单文件、单处、症状即定位：缺陷在 sum 的累加符号，Agent 直接读该文件即可修好，无需探索或委派。',
    rationaleNot: 'EXPLORE/DELEGATE/PARALLEL/WORKFLOW/VERIFY/REPLAN 都不是该任务的最小充分动作：没有未知区域需要搜索、没有可并行子任务、失败原因不含状态不一致。',
  }),
  V({
    id: 'FORMAL-F01-A2', category: 'A', variant: 2, token: 'F01-A2 OK',
    title: '单模块两个函数的格式约定修复',
    taskType: 'doc', complexity: 'simple', scope: 'project', characteristics: [], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-A2 的 src/format.js 未满足 usage.js 中记录的约定（连字符词需首字母大写）。修正 src/format.js 使约定成立。不得修改 verify.js。',
    files: {
      'src/format.js': `function titleCase(s) {\n  return s.charAt(0).toUpperCase() + s.slice(1);\n}\nfunction slug(s) {\n  return s.trim().toLowerCase().replace(/\\s+/g, '-');\n}\nmodule.exports = { titleCase, slug };\n`,
      'src/usage.js': `// 约定：title-case 必须把连字符分隔的每个词首字母大写\n//   titleCase('hello-world') === 'Hello-World'\n//   titleCase('a b') === 'A B'\nmodule.exports = {};\n`,
      'verify.js': `const assert = require('assert');\nconst { titleCase, slug } = require('./src/format.js');\nassert.strictEqual(titleCase('hello-world'), 'Hello-World');\nassert.strictEqual(titleCase('a b'), 'A B');\nassert.strictEqual(slug('  Hello World '), 'hello-world');\nconsole.log('F01-A2 OK');\n`,
    },
    fix: { 'src/format.js': `function titleCase(s) {\n  return s.replace(/(^|[\\s-])(\\w)/g, (_m, p1, p2) => p1 + p2.toUpperCase());\n}\nfunction slug(s) {\n  return s.trim().toLowerCase().replace(/\\s+/g, '-');\n}\nmodule.exports = { titleCase, slug };\n` },
    required: ['format_fixed', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [{ id: 'format_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-A2/verify.js` }],
    expected: ['DIRECT', 'EXPLORE'], expectedDelegation: false,
    rationaleGt: '仍是单模块修复；但"正确格式"写在 usage.js 里，Agent 需要看一眼约定文件——因此 EXPLORE 与 DIRECT 都算最小充分动作。',
    rationaleNot: 'DELEGATE/PARALLEL/WORKFLOW 超出必要（无独立子任务）；REPLAN 不适用（仓库状态自洽，只是实现不符约定）。',
  }),
  V({
    id: 'FORMAL-F01-B1', category: 'B', variant: 1, token: 'F01-B1 OK',
    title: '三段式数据管道的取值丢失定位',
    taskType: 'doc', complexity: 'medium', scope: 'project', characteristics: ['multi_file'], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-B1 的 test.js 失败，但任务书不指出缺陷位于哪个阶段。定位并修复，使 node verify.js 通过。不得修改 verify.js。',
    files: {
      'src/load.js': `function load(raw) {\n  return raw.split(',').map((s) => s.trim()).filter((s) => s !== '');\n}\nmodule.exports = { load };\n`,
      'src/normalize.js': `function normalize(xs) {\n  return xs.map((x) => x.toLowerCase()).filter((x) => x.length >= 0 && x.startsWith('a'));\n}\nmodule.exports = { normalize };\n`,
      'src/summarize.js': `function summarize(xs) {\n  return { count: xs.length, items: xs };\n}\nmodule.exports = { summarize };\n`,
      'test.js': `const { load } = require('./src/load.js');\nconst { normalize } = require('./src/normalize.js');\nconst { summarize } = require('./src/summarize.js');\nconst r = summarize(normalize(load('alpha, beta, gamma')));\nconsole.log('count=' + r.count);\n`,
      'EXPECTED.md': `# 期望\n输入 'alpha, beta, gamma' 经 load → normalize → summarize 后 count 应为 3。\n`,
      'verify.js': `const assert = require('assert');\nconst { load } = require('./src/load.js');\nconst { normalize } = require('./src/normalize.js');\nconst { summarize } = require('./src/summarize.js');\nconst r = summarize(normalize(load('alpha, beta, gamma')));\nassert.strictEqual(r.count, 3);\nconsole.log('F01-B1 OK');\n`,
    },
    fix: { 'src/normalize.js': `function normalize(xs) {\n  return xs.map((x) => x.toLowerCase());\n}\nmodule.exports = { normalize };\n` },
    required: ['pipeline_fixed', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [{ id: 'pipeline_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-B1/verify.js` }],
    expected: ['EXPLORE'], expectedDelegation: false,
    rationaleGt: '缺陷位置未给出，且症状（count 变少）出现在管道末端；必须先沿数据流探查才能定位（normalize 里多了一个 startsWith(\'a\') 过滤），这正是 EXPLORE 的定义。',
    rationaleNot: 'DIRECT 会导致盲改；DELEGATE/PARALLEL/WORKFLOW 对 3 个小文件属过度动作；REPLAN 不适用（无状态不一致）。',
  }),
  V({
    id: 'FORMAL-F01-B2', category: 'B', variant: 2, token: 'F01-B2 OK',
    title: '合计金额偏差的舍入位置排查',
    taskType: 'doc', complexity: 'medium', scope: 'project', characteristics: ['multi_file'], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-B2 的合计与明细不一致（见 REPORT.md）。请修复该问题，使 node verify.js 通过。不得修改 verify.js。',
    files: {
      'src/calc.js': `function lineTotal(qty, price) {\n  return qty * price;\n}\nfunction total(lines) {\n  return lines.reduce((s, l) => s + lineTotal(l.qty, l.price), 0);\n}\nmodule.exports = { lineTotal, total };\n`,
      'src/fmt.js': `function money(x) {\n  return Math.round(x * 10) / 10;\n}\nmodule.exports = { money };\n`,
      'REPORT.md': `# 现象\n明细：3 × 0.335 = 1.005；两行明细合计应为 2.01，但页面显示 2.0（差 0.01）。\n`,
      'verify.js': `const assert = require('assert');\nconst { total } = require('./src/calc.js');\nconst { money } = require('./src/fmt.js');\nassert.strictEqual(money(total([{ qty: 3, price: 0.335 }, { qty: 3, price: 0.335 }])), 2.01);\nconsole.log('F01-B2 OK');\n`,
    },
    fix: { 'src/fmt.js': `function money(x) {\n  return Math.round(x * 100) / 100;\n}\nmodule.exports = { money };\n` },
    required: ['rounding_fixed', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [{ id: 'rounding_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-B2/verify.js` }],
    expected: ['EXPLORE'], expectedDelegation: false,
    rationaleGt: '现象只给出"合计差 0.01"，缺陷可能在 calc 或 fmt；必须探查两层才能确认是 fmt 只保留 1 位小数（×10 而非 ×100），故 EXPLORE 是最小充分动作。',
    rationaleNot: 'DIRECT 会先改错文件；委派类动作对两个小文件过度；REPLAN 不适用。',
  }),
  V({
    id: 'FORMAL-F01-C1', category: 'C', variant: 1, token: 'F01-C1 OK',
    title: '三个互不相关的交付物（修复 + 文档 + 配置）',
    taskType: 'ui_upgrade', complexity: 'medium', scope: 'project', characteristics: ['multi_file'], constraints: ['scope_limited', 'no_public_interface_change'],
    prompt: 'pilot-workspace/FORMAL-F01-C1 有三件互相独立的事：① 修 src/calc.js 的折扣计算错误；② 写 NOTES.md，至少 2 条以「结论」开头的要点；③ 修 config.json 的阈值（应为 100 而非 10）。三件都完成且 node verify.js 通过。不得修改 verify.js。',
    files: {
      'src/calc.js': `function discount(price, pct) {\n  return price - (price * pct) / 10;\n}\nmodule.exports = { discount };\n`,
      'config.json': `{ "threshold": 10 }\n`,
      'NOTES.md': `# 说明\n（待补）\n`,
      'verify.js': `const assert = require('assert');\nconst fs = require('fs');\nconst path = require('path');\nconst { discount } = require('./src/calc.js');\nassert.strictEqual(discount(100, 20), 80);\nconst cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'config.json'), 'utf8'));\nassert.strictEqual(cfg.threshold, 100);\nconst notes = fs.readFileSync(path.join(__dirname, 'NOTES.md'), 'utf8');\nassert.ok((notes.match(/^结论/gm) || []).length >= 2, 'NOTES.md 需至少 2 条以「结论」开头的要点');\nconsole.log('F01-C1 OK');\n`,
    },
    fix: {
      'src/calc.js': `function discount(price, pct) {\n  return price - (price * pct) / 100;\n}\nmodule.exports = { discount };\n`,
      'config.json': `{ "threshold": 100 }\n`,
      'NOTES.md': `# 说明\n结论：折扣按百分比换算，pct=20 表示 20%。\n结论：阈值统一为 100。\n`,
    },
    required: ['calc_fixed', 'notes_written', 'config_fixed', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [
      { id: 'calc_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-C1/verify.js` },
      { id: 'notes_written', kind: 'file_contains', path: 'NOTES.md', expect: '结论', min_count: 2 },
      { id: 'config_fixed', kind: 'file_contains', path: 'config.json', expect: '"threshold": 100' },
    ],
    expected: ['DELEGATE', 'PARALLEL', 'WORKFLOW'], expectedDelegation: true,
    rationaleGt: '三件交付物彼此无依赖（代码修复、文档撰写、配置修正），可分解且可并行 ⇒ 委派/并行/workflow 都是最小充分动作。',
    rationaleNot: 'DIRECT/EXPLORE 会把可分解工作串行化，未利用结构的可并行性；REPLAN 不适用（状态自洽）。',
  }),
  V({
    id: 'FORMAL-F01-C2', category: 'C', variant: 2, token: 'F01-C2 OK',
    title: '两个独立模块 + 一份汇总',
    taskType: 'doc', complexity: 'medium', scope: 'project', characteristics: ['multi_file'], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-C2：① 修 src/left.js 使 verify-left.js 通过；② 修 src/right.js 使 verify-right.js 通过；③ 写 SUMMARY.md，含一行以「汇总」开头的结论。不得修改 verify-left.js / verify-right.js / verify.js。',
    files: {
      'src/left.js': `function last(xs) {\n  return xs[xs.length];\n}\nmodule.exports = { last };\n`,
      'src/right.js': `function uniq(xs) {\n  return xs;\n}\nmodule.exports = { uniq };\n`,
      'verify-left.js': `const assert = require('assert');\nconst { last } = require('./src/left.js');\nassert.strictEqual(last([1, 2, 3]), 3);\nconsole.log('LEFT OK');\n`,
      'verify-right.js': `const assert = require('assert');\nconst { uniq } = require('./src/right.js');\nassert.deepStrictEqual(uniq([1, 1, 2]), [1, 2]);\nconsole.log('RIGHT OK');\n`,
      'SUMMARY.md': `# 汇总\n（待补）\n`,
      'verify.js': `const assert = require('assert');\nconst fs = require('fs');\nconst path = require('path');\nconst { last } = require('./src/left.js');\nconst { uniq } = require('./src/right.js');\nassert.strictEqual(last([1, 2, 3]), 3);\nassert.deepStrictEqual(uniq([1, 1, 2]), [1, 2]);\nassert.ok(/^汇总/m.test(fs.readFileSync(path.join(__dirname, 'SUMMARY.md'), 'utf8')));\nconsole.log('F01-C2 OK');\n`,
    },
    fix: {
      'src/left.js': `function last(xs) {\n  return xs[xs.length - 1];\n}\nmodule.exports = { last };\n`,
      'src/right.js': `function uniq(xs) {\n  return [...new Set(xs)];\n}\nmodule.exports = { uniq };\n`,
      'SUMMARY.md': `# 汇总\n汇总：两个模块各自独立修复，互不影响。\n`,
    },
    required: ['left_fixed', 'right_fixed', 'summary_written', 'verify_pass'], forbidden: ['verify_script_changed'],
    protectedExtra: ['verify-left.js', 'verify-right.js'],
    extraChecks: [
      { id: 'left_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-C2/verify-left.js` },
      { id: 'right_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-C2/verify-right.js` },
      { id: 'summary_written', kind: 'file_contains', path: 'SUMMARY.md', expect: '汇总' },
    ],
    expected: ['DELEGATE', 'PARALLEL', 'WORKFLOW'], expectedDelegation: true,
    rationaleGt: '两个模块互不依赖，各自有独立验收脚本，再加一份汇总 ⇒ 天然可分解/可并行。',
    rationaleNot: 'DIRECT/EXPLORE 未利用可分解性；REPLAN 不适用。',
  }),
  V({
    id: 'FORMAL-F01-D1', category: 'D', variant: 1, token: 'F01-D1 OK',
    title: '三个独立子包的同构修复（需要并行编排）',
    taskType: 'doc', complexity: 'high', scope: 'project', characteristics: ['multi_file'], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-D1 下 pkg1/pkg2/pkg3 各自带一个独立缺陷与独立验收脚本（check1/2/3.js），三者互不共享文件。全部修好并让 node verify.js 通过。不得修改 check*.js 与 verify.js。',
    files: {
      'pkg1/src.js': `function clamp(v, lo, hi) {\n  return Math.min(lo, Math.max(hi, v));\n}\nmodule.exports = { clamp };\n`,
      'pkg2/src.js': `function chunk(xs, n) {\n  const out = [];\n  for (let i = 0; i < xs.length; i += n) out.push(xs.slice(i, i + n + 1));\n  return out;\n}\nmodule.exports = { chunk };\n`,
      'pkg3/src.js': `function sumBy(xs, f) {\n  return xs.reduce((s, x) => s + f(x), 1);\n}\nmodule.exports = { sumBy };\n`,
      'check1.js': `const assert = require('assert');\nconst { clamp } = require('./pkg1/src.js');\nassert.strictEqual(clamp(5, 0, 10), 5);\nassert.strictEqual(clamp(-1, 0, 10), 0);\nassert.strictEqual(clamp(99, 0, 10), 10);\nconsole.log('PKG1 OK');\n`,
      'check2.js': `const assert = require('assert');\nconst { chunk } = require('./pkg2/src.js');\nassert.deepStrictEqual(chunk([1, 2, 3, 4], 2), [[1, 2], [3, 4]]);\nconsole.log('PKG2 OK');\n`,
      'check3.js': `const assert = require('assert');\nconst { sumBy } = require('./pkg3/src.js');\nassert.strictEqual(sumBy([1, 2, 3], (x) => x), 6);\nconsole.log('PKG3 OK');\n`,
      'verify.js': `require('./check1.js');\nrequire('./check2.js');\nrequire('./check3.js');\nconsole.log('F01-D1 OK');\n`,
    },
    fix: {
      'pkg1/src.js': `function clamp(v, lo, hi) {\n  return Math.max(lo, Math.min(hi, v));\n}\nmodule.exports = { clamp };\n`,
      'pkg2/src.js': `function chunk(xs, n) {\n  const out = [];\n  for (let i = 0; i < xs.length; i += n) out.push(xs.slice(i, i + n));\n  return out;\n}\nmodule.exports = { chunk };\n`,
      'pkg3/src.js': `function sumBy(xs, f) {\n  return xs.reduce((s, x) => s + f(x), 0);\n}\nmodule.exports = { sumBy };\n`,
    },
    required: ['pkg1_fixed', 'pkg2_fixed', 'pkg3_fixed', 'verify_pass'], forbidden: ['verify_script_changed'],
    protectedExtra: ['check1.js', 'check2.js', 'check3.js'],
    extraChecks: [
      { id: 'pkg1_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-D1/check1.js` },
      { id: 'pkg2_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-D1/check2.js` },
      { id: 'pkg3_fixed', kind: 'command_exit_zero', command: `node pilot-workspace/FORMAL-F01-D1/check3.js` },
    ],
    expected: ['PARALLEL', 'WORKFLOW'], expectedDelegation: true,
    rationaleGt: '三个子包文件完全不相交、各有独立验收脚本，且合计工作量明显超出单点修复 ⇒ 正确动作是利用并行结构（PARALLEL）或用 workflow 编排。',
    rationaleNot: 'DIRECT/EXPLORE 未利用结构；DELEGATE（单次委派）不足以刻画"三路并行"的必要性 ⇒ 按 Pilot 的 D 类等价集，DELEGATE 不算命中；REPLAN 不适用。',
  }),
  V({
    id: 'FORMAL-F01-D2', category: 'D', variant: 2, token: 'F01-D2 OK',
    title: '两份独立数据集分析与一份合并结论',
    taskType: 'doc', complexity: 'high', scope: 'project', characteristics: ['multi_file'], constraints: ['scope_limited'],
    prompt: 'pilot-workspace/FORMAL-F01-D2：① 由 data/a.csv 生成 report-a.md（含一行以「A 结论」开头的结论）；② 由 data/b.csv 生成 report-b.md（含一行以「B 结论」开头的结论）；③ 写 SUMMARY.md，含一行以「合并」开头的结论。两份分析互不依赖。不得修改 verify.js。',
    files: {
      'data/a.csv': `k,v\nx,1\ny,2\nz,3\n`,
      'data/b.csv': `k,v\np,10\nq,20\n`,
      'report-a.md': `（待生成）\n`,
      'report-b.md': `（待生成）\n`,
      'SUMMARY.md': `（待生成）\n`,
      'verify.js': `const assert = require('assert');\nconst fs = require('fs');\nconst path = require('path');\nconst rd = (f) => fs.readFileSync(path.join(__dirname, f), 'utf8');\nassert.ok(/^A 结论/m.test(rd('report-a.md')), 'report-a.md 需含「A 结论」开头的行');\nassert.ok(/^B 结论/m.test(rd('report-b.md')), 'report-b.md 需含「B 结论」开头的行');\nassert.ok(/^合并/m.test(rd('SUMMARY.md')), 'SUMMARY.md 需含「合并」开头的行');\nconsole.log('F01-D2 OK');\n`,
    },
    fix: {
      'report-a.md': `# A 报告\nA 结论：a.csv 共 3 行，v 合计 6，均值 2。\n`,
      'report-b.md': `# B 报告\nB 结论：b.csv 共 2 行，v 合计 30，均值 15。\n`,
      'SUMMARY.md': `# 汇总\n合并：两组数据规模不同（3 行 vs 2 行），均值差 13。\n`,
    },
    required: ['report_a_written', 'report_b_written', 'summary_written', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [
      { id: 'report_a_written', kind: 'file_contains', path: 'report-a.md', expect: 'A 结论' },
      { id: 'report_b_written', kind: 'file_contains', path: 'report-b.md', expect: 'B 结论' },
      { id: 'summary_written', kind: 'file_contains', path: 'SUMMARY.md', expect: '合并' },
    ],
    expected: ['PARALLEL', 'WORKFLOW'], expectedDelegation: true,
    rationaleGt: '两份分析输入不同、产物不同、彼此无依赖，第三份是两者的汇总 ⇒ 并行/编排是正确动作结构。',
    rationaleNot: 'DIRECT/EXPLORE 串行化；DELEGATE 单路不足以覆盖两路并行（Pilot D 类等价集不含 DELEGATE）；REPLAN 不适用。',
  }),
  V({
    id: 'FORMAL-F01-E1', category: 'E', variant: 1, token: 'F01-E1 OK',
    title: '已有实现的方案性冲突：冻结的累加器契约与精确性要求不能同时满足',
    taskType: 'bugfix', complexity: 'medium', scope: 'project',
    characteristics: ['multi_file'], constraints: ['scope_limited', 'no_public_interface_change'],
    prompt: [
      'pilot-workspace/FORMAL-F01-E1 的 src/stats.js 是一版**已经交付过**的实现（常量内存流式累加器），',
      '它的数值行为被 baseline-accumulator.json 冻结（外部系统按该文件回放快照）。',
      'attempt-log.txt 记录了针对当前实现的一次实际执行结果。',
      'SPEC.md 列出的要求必须同时成立；check.js 与 src/stats.js 都不得修改。',
      '请让 node verify.js 通过。',
    ].join('\n'),
    files: {
      'SPEC.md': [
        '# 必须同时成立的要求',
        '',
        'A. 精确性：平均值的计算结果必须精确到 2 位小数（含抵消型输入，如 [1e16, 1, -1e16]）。',
        'B. 冻结契约：src/stats.js 中 createAccumulator() 的数值行为已被 external baseline 冻结，',
        '   snapshot() 必须与 baseline-accumulator.json 中记录的值**逐位一致**；src/stats.js 不得修改。',
        'C. 接口不变：createAccumulator 必须继续从 src/index.js 导出（调用方依赖它）。',
        'D. check.js 不得修改，也不得通过删除断言来获得通过。',
      ].join('\n'),
      'src/stats.js': [
        '// 方案 X：常量内存流式累加器（数值行为被 external baseline 冻结，不得修改本文件）',
        'function createAccumulator() {',
        '  let sum = 0;',
        '  let n = 0;',
        '  return {',
        '    push(x) {',
        '      sum = Math.fround(sum + Math.fround(x));',
        '      n += 1;',
        '    },',
        '    snapshot() {',
        '      return { sum, n, avg: n ? Math.fround(sum / n) : 0 };',
        '    },',
        '  };',
        '}',
        'function average(xs) {',
        '  const a = createAccumulator();',
        '  for (const x of xs) a.push(x);',
        '  return a.snapshot().avg;',
        '}',
        'module.exports = { average, createAccumulator };',
      ].join('\n'),
      'src/index.js': [
        "const { average, createAccumulator } = require('./stats.js');",
        'module.exports = { average, createAccumulator };',
      ].join('\n'),
      'baseline-accumulator.json': JSON.stringify(
        {
          note: 'external baseline：snapshot() 必须与之逐位一致',
          sequences: [
            { values: [1, 2, 3], snapshot: { sum: 6, n: 3, avg: 2 } },
            { values: [4, 5, 6], snapshot: { sum: 15, n: 3, avg: 5 } },
          ],
        },
        null,
        2,
      ),
      // attempt-log.txt 不在此静态声明：由交付前的**真实预跑**产生（见 preRun）
      'check.js': [
        "const assert = require('assert');",
        "const fs = require('fs');",
        "const path = require('path');",
        "const { average, createAccumulator } = require('./src/index.js');",
        "const baseline = JSON.parse(fs.readFileSync(path.join(__dirname, 'baseline-accumulator.json'), 'utf8'));",
        '// A) 精确性（含抵消型输入）',
        'assert.strictEqual(average([1e16, 1, -1e16]), 1 / 3);',
        'assert.strictEqual(average([0.1, 0.2, 0.3]), 0.2);',
        '// B) 冻结累加器行为（逐位一致）',
        'for (const seq of baseline.sequences) {',
        '  const a = createAccumulator();',
        '  for (const x of seq.values) a.push(x);',
        '  assert.deepStrictEqual(a.snapshot(), seq.snapshot);',
        '}',
        "console.log('CHECK OK');",
      ].join('\n'),
      'verify.js': "require('./check.js');\nconsole.log('F01-E1 OK');\n",
    },
    fix: {
      'src/exact.js': [
        '// 精确路径：按 2 位小数放大为整数后用 BigInt 求和（不触碰冻结的 stats.js）',
        'function exactMean(xs) {',
        '  let t = 0n;',
        '  for (const x of xs) t += BigInt(Math.round(x * 100));',
        '  return Number(t) / (100 * xs.length);',
        '}',
        'module.exports = { exactMean };',
      ].join('\n'),
      'src/index.js': [
        "const { createAccumulator } = require('./stats.js');",
        "const { exactMean } = require('./exact.js');",
        'function average(xs) {',
        '  return exactMean(xs);',
        '}',
        'module.exports = { average, createAccumulator };',
      ].join('\n'),
    },
    preRun: { command: 'node pilot-workspace/FORMAL-F01-E1/check.js', log: 'pilot-workspace/FORMAL-F01-E1/attempt-log.txt' },
    protectedExtra: ['src/stats.js', 'check.js'],
    required: ['exact_path_added', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [{ id: 'exact_path_added', kind: 'file_exists', path: 'pilot-workspace/FORMAL-F01-E1/src/exact.js' }],
    expected: ['REPLAN'], expectedDelegation: false,
    rationaleGt: [
      '**既有方案已失败且继续原路径不再成立**：现有一版实现（常量内存 float32 累加器）已被 baseline 冻结，',
      '而 check.js 记录到精确性断言失败；attempt-log.txt 记载了对 stats.js 的两条直接修法（提精度、放宽断言）各自违反 B 或 D。',
      '在"只动出问题的 stats.js"这条路径下，A 与 B 无法同时满足 ⇒ 必须**重新判断实现路径**（把精确性与流式统计分成两条路径、',
      '并决定哪条契约保持不变），这属于计划层的重新规划，而不是对现有代码的局部修补。',
      '因此 REPLAN 是该状态下的**最小充分**首决策。',
    ].join(''),
    rationaleNot: [
      'DIRECT/EXPLORE 不成立：问题不在"未看清范围"，而在**既有方案本身不可继续**（改 stats.js 必破坏冻结契约）。',
      'VERIFY 不成立：任务目标不是验证已有结果，而是处理已失败的实现方案。',
      '委派类（DELEGATE/PARALLEL/WORKFLOW）不成立：这里只有一个相互冲突的实现路径要重新判断，没有可分解的独立子任务。',
    ].join(''),
  }),
  V({
    id: 'FORMAL-F01-E2', category: 'E', variant: 2, token: 'F01-E2 OK',
    title: '失败管线：配置 / 生成脚本 / 输入格式三者不一致，单点改路径无法满足约束',
    taskType: 'data_layer', complexity: 'medium', scope: 'project',
    characteristics: ['multi_file'], constraints: ['scope_limited', 'data_schema_immutable'],
    prompt: [
      'pilot-workspace/FORMAL-F01-E2 的数据管线上一轮运行失败，日志见 pipeline.log。',
      'config.json、generator（gen.js）与当前输入 data/input.txt 三者的状态记录在 pipeline.log。',
      'config.schema.json 与 check.js 都不得修改（也不得削弱校验）；config.json 必须满足 config.schema.json。',
      '请让 node verify.js 通过。',
    ].join('\n'),
    files: {
      'config.json': '{ "input": "data/missing.txt", "format_version": 2 }\n',
      'config.schema.json': JSON.stringify(
        {
          title: 'pipeline config schema（不得修改）',
          required: ['input', 'format_version'],
          format_version_enum: [2, 3],
          note: 'format_version 只允许 2 或 3；input 必须指向实际存在且版本一致的文件',
        },
        null,
        2,
      ),
      'gen.js': [
        '// 生成器（不得修改）：产出 format v3 的输入文件',
        "const fs = require('fs');",
        "const path = require('path');",
        "const out = path.join(__dirname, 'data', 'input.txt');",
        "fs.mkdirSync(path.dirname(out), { recursive: true });",
        "fs.writeFileSync(out, 'v3\\n' + 'a,1\\nb,2\\n', 'utf8');",
        "console.log('generated v3 -> data/input.txt');",
      ].join('\n'),
      'migrate.js': [
        '// 迁移器（可用）：把已存在的 v1 输入升级为 v2',
        "const fs = require('fs');",
        "const path = require('path');",
        "const p = path.join(__dirname, 'data', 'input.txt');",
        "const text = fs.readFileSync(p, 'utf8');",
        "if (!text.startsWith('v1')) { console.error('不是 v1，无法迁移'); process.exit(1); }",
        "fs.writeFileSync(p, text.replace(/^v1/, 'v2'), 'utf8');",
        "console.log('migrated v1 -> v2');",
      ].join('\n'),
      'data/input.txt': 'v1\na,1\nb,2\n',
      // pipeline.log 不在此静态声明：由交付前的**真实预跑**产生（见 preRun）
      'check.js': [
        "const assert = require('assert');",
        "const fs = require('fs');",
        "const path = require('path');",
        "const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'config.json'), 'utf8'));",
        "const schema = JSON.parse(fs.readFileSync(path.join(__dirname, 'config.schema.json'), 'utf8'));",
        "assert.ok(schema.format_version_enum.includes(cfg.format_version), 'format_version 必须 ∈ ' + JSON.stringify(schema.format_version_enum));",
        "const input = path.join(__dirname, cfg.input);",
        "assert.ok(fs.existsSync(input), '输入不存在：' + cfg.input);",
        "const head = fs.readFileSync(input, 'utf8').split('\\n')[0].trim();",
        "assert.strictEqual(head, 'v' + cfg.format_version, '输入版本 ' + head + ' 与 config.format_version=' + cfg.format_version + ' 不一致');",
        "console.log('CONFIG OK');",
      ].join('\n'),
      'verify.js': "require('./check.js');\nconsole.log('F01-E2 OK');\n",
    },
    fix: {
      'config.json': '{ "input": "data/input.txt", "format_version": 2 }\n',
      'data/input.txt': 'v2\na,1\nb,2\n',
    },
    preRun: { command: 'node pilot-workspace/FORMAL-F01-E2/check.js', log: 'pilot-workspace/FORMAL-F01-E2/pipeline.log' },
    protectedExtra: ['config.schema.json', 'check.js', 'gen.js'],
    required: ['pipeline_consistent', 'verify_pass'], forbidden: ['verify_script_changed'],
    extraChecks: [{ id: 'pipeline_consistent', kind: 'command_exit_zero', command: 'node pilot-workspace/FORMAL-F01-E2/check.js' }],
    expected: ['REPLAN'], expectedDelegation: false,
    rationaleGt: [
      '**既有配置方案已运行且已失败**（pipeline.log），且三件产物互相不一致：config 指向不存在的文件、',
      '现存输入为 v1、生成器产出 v3、而 schema 只允许 {2,3}。check.js 保护"版本与配置必须一致"，schema 又冻结了枚举值。',
      '因此"只改路径"（最直接的局部修法）必然失败：路径修好后版本仍不一致；把 format_version 改成 1 又被 schema 拒绝。',
      '可行方向至少有两条且互相排斥：① 重跑生成器产出 v3 并把 config 改为 3；② 用迁移器把现有输入升级为 v2 并保持 config=2。',
      '选择哪条路径、以及随之而来的数据重建范围，属于**计划层判断**，必须先 REPLAN 再执行 ⇒ REPLAN 是最小充分首决策。',
    ].join(''),
    rationaleNot: [
      'DIRECT 不成立：直接改 config.input 之后 check 仍然失败（版本不一致），局部修补无法收敛。',
      'EXPLORE 不成立：失败原因已在 pipeline.log 中明确列出，不存在"范围未知需要先看"的成分。',
      'VERIFY 不成立：任务目标不是验证已有结果。',
      '委派类不成立：这里是一条需要重新定方向的管线，没有可并行的独立子任务。',
    ].join(''),
  }),
];

// ---------- 生成种子模块、任务 YAML 与证据 ----------
const seedEntries: Array<{ path: string; content: string }> = [
  { path: 'pilot-workspace/package.json', content: '{"type":"commonjs"}\n' },
];
const evidence: Array<{ id: string; before: number | null; after: number | null; note: string }> = [];
rmSync(EVIDENCE_DIR, { recursive: true, force: true });
mkdirSync(TASKS_DIR, { recursive: true });

for (const v of variants) {
  const base = `pilot-workspace/${v.id}`;
  for (const [rel, content] of Object.entries(v.files)) {
    seedEntries.push({ path: `${base}/${rel}`, content });
  }
  const uniform: Array<Record<string, unknown>> = [
    { id: 'verify_pass', kind: 'output_contains', command: `node ${base}/verify.js`, expect: v.token },
    { id: 'verify_script_changed', kind: 'file_unchanged', path: `${base}/verify.js` },
  ];
  const checks: Array<Record<string, unknown>> = [...uniform, ...(v.extraChecks ?? [])];
  const yaml = [
    `id: ${v.id}`,
    `category: ${v.category}`,
    'status: draft',
    'source: synthetic-formal',
    `task_type: ${v.taskType}`,
    `complexity: ${v.complexity}`,
    `scope: ${v.scope}`,
    `characteristics: [${v.characteristics.join(', ')}]`,
    `constraints: [${v.constraints.join(', ')}]`,
    'prompt: |',
    ...v.prompt.split('\n').map((l) => `  ${l}`),
    `expected_first_decisions: [${v.expected.join(', ')}]`,
    `expected_delegation: ${String(v.expectedDelegation)}`,
    'success_criteria:',
    '  required:',
    ...v.required.map((r) => `    - ${r}`),
    '  forbidden:',
    ...v.forbidden.map((f) => `    - ${f}`),
    'expected_files:',
    ...Object.keys(v.fix).map((f) => `  - ${base}/${f}`),
    'allowed_paths:',
    `  - ${base}/**`,
    'protected_paths:',
    `  - ${base}/verify.js`,
    ...(v.protectedExtra ?? []).map((p) => `  - ${p.startsWith('pilot-workspace/') ? p : `${base}/${p}`}`),
    'verification:',
    ...checks.flatMap((c) => {
      const lines = [`  - id: ${String(c['id'])}`, `    kind: ${String(c['kind'])}`];
      if (c['command'] !== undefined) lines.push(`    command: ${String(c['command'])}`);
      if (c['expect'] !== undefined) lines.push(`    expect: ${JSON.stringify(String(c['expect']))}`);
      if (c['path'] !== undefined) {
        const p = String(c['path']);
        lines.push(`    path: ${p.startsWith('pilot-workspace/') ? p : `${base}/${p}`}`);
      }
      if (c['min_count'] !== undefined) lines.push(`    min_count: ${String(c['min_count'])}`);
      return lines;
    }),
    '',
  ].join('\n');
  writeFileSync(path.join(TASKS_DIR, `${v.id}.yaml`), yaml, 'utf8');

  // 证据：未修复必须失败、参考修复后必须通过（在证据目录内，不污染正式种子）
  const evDir = path.join(EVIDENCE_DIR, v.id);
  mkdirSync(path.join(evDir, 'src'), { recursive: true });
  mkdirSync(path.join(evDir, 'pkg1', 'src'), { recursive: true });
  mkdirSync(path.join(evDir, 'data'), { recursive: true });
  for (const [rel, content] of Object.entries(v.files)) {
    const p = path.join(evDir, rel);
    mkdirSync(path.dirname(p), { recursive: true });
    writeFileSync(p, content, 'utf8');
  }
  const runVerify = (): number | null => {
    try {
      execFileSync(process.execPath, ['verify.js'], { cwd: evDir, stdio: 'inherit', timeout: 60_000 });
      return 0;
    } catch (e) {
      return (e as { status?: number | null }).status ?? null;
    }
  };
  const before = runVerify();
  for (const [rel, content] of Object.entries(v.fix)) {
    const p = path.join(evDir, rel);
    mkdirSync(path.dirname(p), { recursive: true });
    writeFileSync(p, content, 'utf8');
  }
  const after = runVerify();
  evidence.push({ id: v.id, before, after, note: before !== 0 && after === 0 ? '先失败后通过 ✓' : '⚠️ 证据不成立，见族级审核包' });
}

// ---------- 校验（loadTask：schema + 候选集 + 委派轴） ----------
const loadResults = variants.map((v) => {
  const file = path.join(TASKS_DIR, `${v.id}.yaml`);
  const loaded = loadTask(parseYaml(readFileSync(file, 'utf8')) as Record<string, unknown>);
  if (!loaded.ok) console.log(`    [诊断] ${v.id} 加载失败，返回字段 = ${Object.keys(loaded).join(', ')}`);
  return { v, loaded };
});

// ---------- 交付前流程 + 正式判定路径证据（真实预跑 → 日志 → 冻结 baseline → verifyTask） ----------
process.env['DSH_VERIFY_DATASET'] = 'formal';
process.env['DSH_FORMAL_BASELINE'] = path.join(ROOT, 'pilot-workspace', '.formal-baseline.selfcheck.json');
const vtEvidence: Array<{ id: string; beforeOk: boolean | null; afterOk: boolean | null; status: string; cfg: number; pre?: string }> = [];
{
  // ① 播种**未修复**状态（失败日志尚未存在）
  for (const v of variants) {
    const dir = path.join(ROOT, 'pilot-workspace', v.id);
    rmSync(dir, { recursive: true, force: true });
    for (const [rel, content] of Object.entries(v.files)) {
      const p = path.join(dir, rel);
      mkdirSync(path.dirname(p), { recursive: true });
      writeFileSync(p, content, 'utf8');
    }
  }
  // ② 预跑既定 check，把真实 exit_code / stdout / stderr 写成失败日志
  //    允许的副作用仅限：执行既定 check + 产生声明的日志文件（不改源码/GT/schema/check.js）
  const preRunExit = new Map<string, number>();
  for (const v of variants) {
    if (!v.preRun) continue;
    const script = path.join(ROOT, v.preRun.command.split(' ')[1]!);
    const outTmp = path.join(ROOT, 'pilot-workspace', '.prerun-' + v.id + '.out');
    const errTmp = path.join(ROOT, 'pilot-workspace', '.prerun-' + v.id + '.err');
    const of = openSync(outTmp, 'w');
    const ef = openSync(errTmp, 'w');
    let code = 0;
    try {
      execFileSync(process.execPath, [script], { cwd: ROOT, stdio: ['ignore', of, ef], timeout: 60_000 });
    } catch (e) {
      const st = (e as { status?: number | null }).status;
      code = typeof st === 'number' ? st : 1;
    } finally {
      closeSync(of);
      closeSync(ef);
    }
    const stdout = readFileSync(outTmp, 'utf8');
    const stderr = readFileSync(errTmp, 'utf8');
    writeFileSync(
      path.join(ROOT, v.preRun.log),
      ['# 预跑记录（冻结环境中实际执行，非人工撰写）', 'command: ' + v.preRun.command, 'exit_code: ' + String(code), 'stdout:', stdout.trim(), 'stderr:', stderr.trim(), ''].join('\n'),
      'utf8',
    );
    rmSync(outTmp, { force: true });
    rmSync(errTmp, { force: true });
    preRunExit.set(v.id, code);
    console.log('  预跑 ' + v.id + '：' + v.preRun.command + ' → exit=' + String(code) + '（日志已写入 ' + v.preRun.log + '）');
  }
  // ③ **日志生成之后**才冻结 formal baseline（baseline 代表 Agent 实际接手的完整状态）
  const bl = buildBaselineFromWorkspace({ taskSetId: 'F01', taskIds: variants.map((v) => v.id) }, { force: true });
  console.log('  formal baseline 已冻结（含预跑日志）：' + Object.keys(bl.files).length + ' 个文件，baseline_hash=' + bl.baseline_hash.slice(0, 12) + '…');
  // ④ 逐变体判定：未修复 → verifyTask（应 FAIL）→ 参考修复 → verifyTask（应 PASS）
  for (const { v, loaded } of loadResults) {
    if (!loaded.ok) {
      vtEvidence.push({ id: v.id, beforeOk: null, afterOk: null, status: 'SCHEMA_FAIL', cfg: 0 });
      continue;
    }
    const before = verifyTask(loaded.task);
    for (const [rel, content] of Object.entries(v.fix)) {
      const p = path.join(ROOT, 'pilot-workspace', v.id, rel);
      mkdirSync(path.dirname(p), { recursive: true });
      writeFileSync(p, content, 'utf8');
    }
    const after = verifyTask(loaded.task);
    vtEvidence.push({
      id: v.id,
      beforeOk: before.success,
      afterOk: after.success,
      status: String(after.verification_status),
      cfg: after.config_errors.length,
      pre: v.preRun ? 'exit=' + String(preRunExit.get(v.id)) : undefined,
    });
    rmSync(path.join(ROOT, 'pilot-workspace', v.id), { recursive: true, force: true });
  }
  rmSync(String(process.env['DSH_FORMAL_BASELINE']), { force: true });
}
delete process.env['DSH_VERIFY_DATASET'];
delete process.env['DSH_FORMAL_BASELINE'];

// ---------- 种子模块 ----------
const seedsTs = `/**
 * benchmark/formal-seeds-f01.ts — F01 族 10 个正式变体的种子（由 scripts/formal-author-f01.ts 生成）
 * 纪律：每个变体的种子独立编写；不含任何 Pilot 锚点的 GT 或内容。
 */
export const FORMAL_F01_SEEDS: Array<{ path: string; content: string }> = ${JSON.stringify(seedEntries, null, 2)};
`;
writeFileSync(SEEDS_MOD, seedsTs, 'utf8');

// ---------- GT 草案（签署字段一律留空） ----------
writeJsonUtf8(GT_DRAFTS, {
  family: 'F01',
  generated_at: new Date().toISOString(),
  signature: { gt_signed_by: '', gt_signed_at: '', status: 'DRAFT — 待人工签署' },
  variants: variants.map((v) => ({
    task_id: v.id, family: 'F01', category: v.category, variant: v.variant, title: v.title,
    task_description: v.prompt,
    expected_first_decisions: v.expected, expected_delegation: v.expectedDelegation,
    candidate_set_check: 'PASS（expected_first_decisions ⊆ FIRST_DECISION 词表，非空）',
    delegation_axis_check: `PASS（由集合推出 expected_delegation=${String(v.expectedDelegation)}，与声明一致）`,
    verification_rules: v.required.map((r) => `${r}${r === 'verify_pass' ? '（output_contains ' + v.token + '）' : ''}`),
    rationale_in_gt: v.rationaleGt,
    rationale_not_in_gt: v.rationaleNot,
    gt_signed_by: '', gt_signed_at: '',
  })),
});

// ---------- 族级审核包 ----------
const md: string[] = [
  '# F01 族级审核包（10 个正式变体 · GT 待签署）',
  '',
  '> 本族任务由生成器起草（status: draft）。**签署只能由人工完成**：',
  '> 签署前 `gt_signed_by`/`gt_signed_at` 留空，正式 manifest 门禁保持 fail-closed。',
  '> 纪律：签署后 GT、期望第一步决策集合、验证规则**不得**因试跑结果调整；',
  '> 若发现作者错误 ⇒ 该任务退回、修订版本重新签署、原版本留下 provenance。',
  '',
  '| task_id | cat | var | expected_first_decisions | expected_delegation | 证据（未修复→参考修复） |',
  '|---|---|---|---|---|---|',
  ...variants.map((v) => {
    const ev = evidence.find((e) => e.id === v.id)!;
    return `| ${v.id} | ${v.category} | ${v.variant} | ${v.expected.join('\\|')} | ${String(v.expectedDelegation)} | exit ${String(ev.before)} → ${String(ev.after)} ${ev.note.includes('✓') ? '✓' : '⚠️'} |`;
  }),
  '',
];
for (const { v, loaded } of loadResults) {
  const ev = evidence.find((e) => e.id === v.id)!;
  md.push(
    `## ${v.id}（${v.category} 类 · 变体 ${v.variant}）`,
    '',
    `**标题**：${v.title}`,
    '',
    '**任务描述**：',
    '```',
    v.prompt,
    '```',
    '',
    `**expected_first_decisions**：\`[${v.expected.join(', ')}]\`　**expected_delegation**：\`${String(v.expectedDelegation)}\``,
    '',
    `- 候选集合校验：${loaded.ok ? 'PASS' : 'FAIL — ' + (JSON.stringify(loaded.issues ?? []))}`,
    `- CDA 布尔轴校验：PASS（派生值 = ${String(v.expectedDelegation)}）`,
    '',
    `**验证规则**：${v.required.join(', ')}（forbidden: ${v.forbidden.join(', ')}）`,
    '',
    `**验证证据**：未修复时 exit=${String(ev.before)}（应非 0）；参考修复后 exit=${String(ev.after)}（应为 0）⇒ ${ev.note}`,
    '',
    `**为什么这些 first_decision 属于 GT**：${v.rationaleGt}`,
    '',
    `**为什么其他候选不属于 GT**：${v.rationaleNot}`,
    '',
    `**签署**：\`gt_signed_by: ________\`　\`gt_signed_at: ________\``,
    '',
  );
}
md.push('', '## 门禁状态', '', '```', `本族任务文件：${variants.length} 个（全部 status: draft）`, `已冻结：0（等待人工签署）`, '```', '');
writeFileSync(REVIEW, md.join('\n'), 'utf8');

console.log('=== F01 起草完成 ===');
console.log(`  任务 YAML：${variants.length} 个（benchmark/tasks/formal/，全部 status: draft）`);
console.log(`  种子模块：benchmark/formal-seeds-f01.ts（${seedEntries.length} 个文件条目）`);
console.log(`  GT 草案：benchmark/formal/f01-gt-drafts.json（签署字段留空）`);
console.log(`  族级审核包：benchmark/formal/f01-review.md`);
console.log('\n  逐变体证据（未修复 exit → 参考修复 exit）：');
for (const e of evidence) console.log(`    ${e.id}  ${String(e.before)} → ${String(e.after)}  ${e.note}`);
console.log('\n  逐变体 schema/候选集校验：');
for (const { v, loaded } of loadResults) {
  console.log(`    ${v.id}  ${loaded.ok ? 'PASS' : 'FAIL：' + (JSON.stringify(loaded.issues ?? []))}`);
}
rmSync(EVIDENCE_DIR, { recursive: true, force: true });
console.log('\n  证据目录已清理（未污染正式种子）');
const allOk = evidence.every((e) => e.before !== 0 && e.after === 0) && loadResults.every((r) => r.loaded.ok);
console.log(allOk ? '✅ 起草与机械证据全部通过（等待人工签署）' : '⛔ 存在问题，见族级审核包');
console.log('\n  正式判定路径证据（verifyTask：未修复 → 参考修复）：');
for (const e of vtEvidence) {
  console.log(`    ${e.id}  ${String(e.beforeOk)} → ${String(e.afterOk)}  ${e.beforeOk === false && e.afterOk === true ? '✓' : '⚠️'}`);
}
const vtOk = vtEvidence.length > 0 && vtEvidence.every((e) => e.beforeOk === false && e.afterOk === true && e.status === 'OK' && e.cfg === 0);
console.log('  verifyTask FAIL→PASS = ' + vtEvidence.filter((e) => e.beforeOk === false && e.afterOk === true).length + '/' + vtEvidence.length + '   CONFIG_ERROR 总数 = ' + vtEvidence.reduce((a, e) => a + e.cfg, 0) + '   success=null 数 = ' + vtEvidence.filter((e) => e.beforeOk === null || e.afterOk === null).length);
process.exit(allOk && vtOk ? 0 : 3);
